Fix compilation issue
On some platform linking stage may fail with the following message:

unnpk.c:(.text+0x3f6): undefined reference to `inflateInit_'
unnpk.c:(.text+0x536): undefined reference to `inflate'
unnpk.c:(.text+0x55d): undefined reference to `inflateEnd'
unnpk.c:(.text+0xc3e): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status

This issue is caused by a wrong compiler arguments order. Instruction
to link with zlib (-lz) goes before the source file and linker can not
found required symbols. Fix this issue by correcting arguments order in
the compiler invocation line.

Thanks to David Jacoby, for the issue report and the solution
suggestion.

Reported-and-tested-by: David Jacoby <david.jacoby@kaspersky.se>